### ISSUE TITLE
Commit link error?

### ISSUE THREAD

**Issue by rhaft** [tosdr/tosback2#32]
Am I the only one who gets a 404 error using the commit link in the daily email?

My July 15 link:
These were changed in last night's crawl. Please have a look at the commit at https://github.com/tosdr/tosback2/commit/dcaa69506e2b89475af4b01c1e1b3125afbdad2b?diff=split to see the differences!

**Comment by zingbretsenucb** [comment]
It looks like the last commit on GitHub is from April 30 for the crawls. Maybe recent changes haven't been pushed up here?

**Comment by JimmStout** [comment]
Should be fixed now. The ssh key needed to be re-authed, and then, the commits were so far behind that the server didn't seem to have enough memory to 'pack' the commits all at once. I pushed them incrementally, and it's caught up now.
