### ISSUE TITLE
Muliple language versions may not be in sync :-(

### ISSUE THREAD

**Issue by grinapo** [tosdr/tosback2#36]
I know that everyone hates such reports: you would think that localised ToS should change with the English "master". Well, nope.

Today I noticed that Google Play have changed their ToS. Or, more precisely:
https://play.google.com/intl/en-us_us/about/play-terms.html - English - December 18, 2017
https://play.google.com/intl/hu_hu/about/play-terms.html - Hungarian - February 5, 2018
possibly similar to
https://play.google.com/intl/en_uk/about/play-terms.html - UK English, Febr 5, 2018

So, first, it seems changes shall be tracked for localised languages, which may be kind of hundredfold amount of data.

Then there is the funny part, when multiple different English versions exist, where they could be happily diffed against one another, to show regional differences between the terms.

(As a sidenote: all the websites are in horrible shape: tosdr.org and especially tosback.org. They are desperately in need of lots of love.)

**Comment by grinapo** [comment]
(Just realised that the actual crawled data for Google ToS is pretty much out of date: was crawled in October, 2017.)

**Comment by JimmStout** [comment]
Thanks for the time you have taken to look into this. Unfortunately, we've not had the time to manage the various languages although there are a few (outdated) rules in place for localized domains (e.g., google.de). We're working on better site tools to make this easier in the future.

> (Just realised that the actual crawled data for Google ToS is pretty much out of date: was crawled in October, 2017.)

AFAIK, that's the last time it changed. However, you may be looking the Google _Play_ ToS, and that appears to be missing from our rules. I'll add it! Thanks!

**Comment by grinapo** [comment]
Indeed. Thanks. 
I18N is a tough problem, I hope sometimes in the future there'll be possibility to offer nationalised rules.
Issue closed (on my part).
