### ISSUE TITLE
TOSBack didn't grab new twitter.com update

### ISSUE THREAD

**Issue by Peter200lx** [tosdr/tosback2#37]
The Twitter TOS and Privacy Policy updated this week:
>We have made revisions to these Terms of Service, effective May 25th, 2018. You can see the new Terms of Service here [https://twitter.com/tos#update]. By continuing to use our services after May 25th, you agree to the new Terms of Service. A summary of changes can be found on our Help Center [https://help.twitter.com/rules-and-policies/update-privacy-policy].

However the version in this repository hasn't been updated in 7 months: `crawl_reviewed/twitter.com`

The URL is the same: https://twitter.com/en/tos
But I think the `xpath` rule no longer is valid. (At least I couldn't find `main-content` from `rules/twitter.com.xml` when looking at the source.)

**Comment by JimmStout** [comment]
Good catch, @Peter200lx! I updated it, and it should get crawled on the server tonight.
