### ISSUE TITLE
ambiguous path i don't understand

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/tosback2#44]
https://trello.com/security:	Ambiguous match, found 2 elements matching visible xpath "//div[@class='layout-centered-content']"

but i can't see the problem when i execute
```js
a=document.evaluate("//div[@class='layout-centered-content']", document, null, XPathResult.ANY_TYPE, null)
a.iterateNext()
a.iterateNext()
```
in the browser console on https://trello.com/legal/security

**Comment by Vinnl** [comment]
When I inspect the source and check the `.layout-centered-content` CSS selector, I get 2 elements as well: the one with the "Trust @ Trello" heading, and the one with the bullet headings for "Security, Legal and Privacy, Availability, Need to report a vulnerability? and Thanks".

**Comment by michielbdejong** [comment]
fixed, i had a typo in the url (/security instead of /legal/security)
