### ISSUE TITLE
Git quirk with Amazon Silk T&C

### ISSUE THREAD

**Issue by secretrobotron** [tosdr/tosback2#62]
Not sure if this is just git on my machine, or if there's something interesting happening in the repo somehow, but no matter how I try to refresh my repo, I get this:

```
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   crawl_reviewed/amazon.com/AMAZON SILK TERMS & CONDITIONS.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

If I use `git reset --hard`, then, only the capitalization changes:

```
        modified:   crawl_reviewed/amazon.com/Amazon Silk Terms & Conditions.txt
```

The actual diff—which is quite large—remains the same.

Any insights?

**Comment by michielbdejong** [comment]
Sounds like an issue on your machine, yes. Apart from upper/lower case, both files have the same filename, so probably this is due to your local file system not handling the filenames properly. Are you on a Windows computer? Are you seeing one or two files now?  And which 'last updated' dates are you seeing at  the top of each? Both files exists in the git repo, the all-caps one is from 2013, the other one from 2017.

**Comment by secretrobotron** [comment]
Yeah, soooo confusing. Only one of the files exists, but it depends on the state of my git repo. If I `git reset --hard` it switches between the upper-case and lower-case version.

I'm on OSX using both the cmd line and github app. The github app is sufficiently confused.

In `crawl_reviewed/amazon.com/AMAZON SILK TERMS & CONDITIONS.txt`, we've got

```
Last updated: February 28, 2013 </strong>
```

And, in `crawl_reviewed/amazon.com/Amazon Silk Terms & Conditions.txt`, I see

```
<strong>Last updated: December 13, 2017 </strong>
```

Again, only one of them exists at any one time. I have to `git reset --hard` to switch between them. 

And, if I `git rm --cached` one of them, the other shows up in `git status`, but ... doesn't actually exist in my filesystem (see below).

![Screen Shot 2019-03-19 at 9 36 24 AM](https://user-images.githubusercontent.com/403231/54610264-0174ed00-4a2b-11e9-982d-c61118ac838a.png)

**Comment by michielbdejong** [comment]
Wow
